# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AJ's Personal Site
email: aalexander05@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here we have a new site to play with. Thanks to the folks at Github for the hosting.
  They're a good bunch o' folks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: AndrewJorda
github_username:  aalexander05

# Build settings
markdown: kramdown
